using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Remove_Palindromic_Subsequences
{
    /// <summary>
    /// Given a string s consisting only of letters 'a' and 'b'. In a single step you can remove one palindromic subsequence from s.
    /// Return the minimum number of steps to make the given string empty.
    /// A string is a subsequence of a given string, if it is generated by deleting some characters of a given string without changing its order.
    /// A string is called palindrome if is one that reads the same backward as well as forward.
    /// </summary>
    public class Solution
    {
        public int RemovePalindromeSub(string s)
        {
            if (string.IsNullOrWhiteSpace(s))
                return 0;

            if (s.Equals(new string(s.Reverse().ToArray())))
                return 1;

            return 2;
        }
    }
}
